include_guard(GLOBAL)

set(SSDF_PUBLIC_DEP_LIBRARIES "")
set(SSDF_PRIVATE_DEP_LIBRARIES "")
set(SSDF_PSDF_PRIVATE_LIBRARIES "")
set(SSDF_PSDF_PRIVATE_INCLUDES "")
set(SSDF_PRIVATE_COMPILE_OPTIONS "")
set(SSDF_PRIVATE_LINK_OPTIONS "")
set(SSDF_BINARY_PRIVATE_COMPILE_OPTIONS "")
set(SSDF_BINARY_PRIVATE_LINK_OPTIONS "")

find_package(smesh CONFIG REQUIRED)
list(APPEND SSDF_PUBLIC_DEP_LIBRARIES smesh::smesh)

function(ssdf_inherit_feature_from_smesh feature_name dependency_token)
    if(NOT TARGET smesh::smesh)
        return()
    endif()

    get_target_property(SSDF_SMESH_LINK_LIBRARIES smesh::smesh INTERFACE_LINK_LIBRARIES)
    if(NOT SSDF_SMESH_LINK_LIBRARIES MATCHES "(^|;)${dependency_token}(;|$)")
        return()
    endif()

    if(NOT ${feature_name})
        message(STATUS "${feature_name} enabled to match smesh")
    endif()
    set(${feature_name} ON CACHE BOOL "" FORCE)
    set(${feature_name} ON PARENT_SCOPE)
endfunction()

ssdf_inherit_feature_from_smesh(SSDF_ENABLE_MPI "MPI::MPI_CXX")
ssdf_inherit_feature_from_smesh(SSDF_ENABLE_OPENMP "OpenMP::OpenMP_CXX")

set(SSDF_NEEDS_OPENMP_RUNTIME ${SSDF_ENABLE_OPENMP})
if(TARGET smesh::smesh)
    get_target_property(SSDF_SMESH_LINK_LIBRARIES smesh::smesh INTERFACE_LINK_LIBRARIES)
    if(SSDF_SMESH_LINK_LIBRARIES MATCHES "(^|;)OpenMP::OpenMP_CXX(;|$)")
        set(SSDF_NEEDS_OPENMP_RUNTIME ON)
    endif()
endif()

if(SSDF_ENABLE_MPI)
    find_package(MPI REQUIRED)
    message(STATUS "MPI found: ${MPI_FOUND}")
    message(STATUS "MPI CXX compiler: ${MPI_CXX_COMPILER}")
    list(APPEND SSDF_PUBLIC_DEP_LIBRARIES MPI::MPI_CXX)
    list(APPEND SSDF_PSDF_PRIVATE_LIBRARIES MPI::MPI_CXX)
endif()

if(SSDF_NEEDS_OPENMP_RUNTIME)
    find_package(OpenMP COMPONENTS CXX REQUIRED)
    message(STATUS "OpenMP found: ${OpenMP_FOUND}")
    message(STATUS "OpenMP CXX: ${OpenMP_CXX_VERSION}")
    message(STATUS "OpenMP CXX flags: ${OpenMP_CXX_FLAGS}")
    list(APPEND SSDF_PUBLIC_DEP_LIBRARIES OpenMP::OpenMP_CXX)
endif()

if(SSDF_ENABLE_CUDA)
    enable_language(CUDA)
    message(STATUS "CUDA enabled")
    set(CMAKE_CUDA_STANDARD 17)
    set(CMAKE_CUDA_STANDARD_REQUIRED ON)

    if(NOT CMAKE_CUDA_ARCHITECTURES)
        set(CMAKE_CUDA_ARCHITECTURES "native")
    endif()
endif()

if(SSDF_ENABLE_HIP)
    enable_language(HIP)
    message(STATUS "HIP enabled")
endif()

if(SSDF_ENABLE_CUBIQL)
    if(NOT cuBQL_DIR)
        message(FATAL_ERROR "cuBQL_DIR is not set")
    endif()
    add_subdirectory(${cuBQL_DIR} "${CMAKE_BINARY_DIR}/_deps/cuBQL-build")
    list(APPEND SSDF_PRIVATE_DEP_LIBRARIES cuBQL)
endif()

if(SSDF_ENABLE_ASAN)
    if(NOT CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        message(FATAL_ERROR "SSDF_ENABLE_ASAN requires Clang or GCC")
    endif()
    if(SSDF_ENABLE_CUDA OR SSDF_ENABLE_HIP)
        message(FATAL_ERROR "SSDF_ENABLE_ASAN does not support CUDA or HIP builds")
    endif()

    list(APPEND SSDF_PRIVATE_COMPILE_OPTIONS -fsanitize=address -fno-omit-frame-pointer)
    list(APPEND SSDF_PRIVATE_LINK_OPTIONS -fsanitize=address)
    list(APPEND SSDF_BINARY_PRIVATE_COMPILE_OPTIONS -fsanitize=address -fno-omit-frame-pointer)
    list(APPEND SSDF_BINARY_PRIVATE_LINK_OPTIONS -fsanitize=address)
endif()

list(APPEND SSDF_PSDF_PRIVATE_INCLUDES "${PROJECT_SOURCE_DIR}")
